-- MySQL Script generated by MySQL Workbench
-- Sun Mar 20 16:29:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetweb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetweb` DEFAULT CHARACTER SET utf8 ;
USE `projetweb` ;

-- -----------------------------------------------------
-- Table `projetweb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetweb`.`client` (
  `numcli` INT NOT NULL,
  `titre` VARCHAR(45) NULL,
  `nomcli` VARCHAR(45) NULL,
  `prenomcli` VARCHAR(45) NULL,
  `mdp` VARCHAR(20) NULL,
  `datedenaiss` DATE NULL,
  `email` VARCHAR(40) NULL,
  `numadr` INT NOT NULL,
  PRIMARY KEY (`numcli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetweb`.`panier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetweb`.`panier` (
  `idpanier` INT NOT NULL,
  `numcom` INT NOT NULL,
  `Qcom` INT NOT NULL,
  `total` INT NULL,
  `numcli` INT NOT NULL,
  `client_numcli` INT NOT NULL,
  PRIMARY KEY (`idpanier`, `client_numcli`),
  INDEX `fk_panier_client1_idx` (`client_numcli` ASC) ,
  CONSTRAINT `fk_panier_client1`
    FOREIGN KEY (`client_numcli`)
    REFERENCES `projetweb`.`client` (`numcli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetweb`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetweb`.`commande` (
  `numcom` INT NOT NULL,
  `numcli` INT NOT NULL,
  `datecom` DATE NULL,
  `quantité` INT NOT NULL,
  `numprod` INT NOT NULL,
  `moyenpaiement` VARCHAR(45) NULL,
  `prixtotal` INT NOT NULL,
  `client_numcli` INT NOT NULL,
  `panier_idpanier` INT NOT NULL,
  PRIMARY KEY (`numcom`, `client_numcli`, `panier_idpanier`, `numprod`),
  INDEX `fk_commande_client1_idx` (`client_numcli` ASC) ,
  INDEX `fk_commande_panier1_idx` (`panier_idpanier` ASC) ,
  CONSTRAINT `fk_commande_client1`
    FOREIGN KEY (`client_numcli`)
    REFERENCES `projetweb`.`client` (`numcli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_panier1`
    FOREIGN KEY (`panier_idpanier`)
    REFERENCES `projetweb`.`panier` (`idpanier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetweb`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetweb`.`produit` (
  `numprod` INT NOT NULL,
  `nomprod` VARCHAR(45) NULL,
  `prix` FLOAT(8,2) NULL,
  `Qstock` INT NULL,
  `taille` VARCHAR(25) NULL,
  `couleur` VARCHAR(25) NULL,
  `typepro` VARCHAR(25) NULL,
  PRIMARY KEY (`numprod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetweb`.`adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetweb`.`adresse` (
  `numadr` INT NOT NULL,
  `nom` VARCHAR(25) NULL,
  `prenom` VARCHAR(25) NULL,
  `tel` INT NOT NULL,
  `pays` VARCHAR(25) NULL,
  `ville` VARCHAR(25) NULL,
  `codepostal` VARCHAR(25) NULL,
  `delegation` VARCHAR(25) NULL,
  `fact` VARCHAR(25) NULL,
  `client_numcli` INT NOT NULL,
  PRIMARY KEY (`numadr`, `client_numcli`),
  INDEX `fk_adresse_client1_idx` (`client_numcli` ASC) VISIBLE,
  CONSTRAINT `fk_adresse_client1`
    FOREIGN KEY (`client_numcli`)
    REFERENCES `projetweb`.`client` (`numcli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetweb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetweb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetweb`.`catégories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetweb`.`catégories` (
  `idcatégories` INT NOT NULL,
  `nomcateg` VARCHAR(45) NULL,
  PRIMARY KEY (`idcatégories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetweb`.`commande_has_produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetweb`.`commande_has_produit` (
  `commande_numcom` INT NOT NULL,
  `produit_numprod` INT NOT NULL,
  PRIMARY KEY (`commande_numcom`, `produit_numprod`),
  INDEX `fk_commande_has_produit_produit1_idx` (`produit_numprod` ASC) VISIBLE,
  INDEX `fk_commande_has_produit_commande1_idx` (`commande_numcom` ASC) VISIBLE,
  CONSTRAINT `fk_commande_has_produit_commande1`
    FOREIGN KEY (`commande_numcom`)
    REFERENCES `projetweb`.`commande` (`numcom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_has_produit_produit1`
    FOREIGN KEY (`produit_numprod`)
    REFERENCES `projetweb`.`produit` (`numprod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetweb`.`produit_has_catégories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetweb`.`produit_has_catégories` (
  `produit_numprod` INT NOT NULL,
  `catégories_idcatégories` INT NOT NULL,
  PRIMARY KEY (`produit_numprod`, `catégories_idcatégories`),
  INDEX `fk_produit_has_catégories_catégories1_idx` (`catégories_idcatégories` ASC) VISIBLE,
  INDEX `fk_produit_has_catégories_produit1_idx` (`produit_numprod` ASC) VISIBLE,
  CONSTRAINT `fk_produit_has_catégories_produit1`
    FOREIGN KEY (`produit_numprod`)
    REFERENCES `projetweb`.`produit` (`numprod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_has_catégories_catégories1`
    FOREIGN KEY (`catégories_idcatégories`)
    REFERENCES `projetweb`.`catégories` (`idcatégories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
